name: Metrics
on:
  schedule:
    - cron: "0 */12 * * *"   # update tiap 12 jam
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: diyosp
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Jakarta
          # Boleh tambah nama/alias author commitmu di sini biar pencocokan rapi:
          commits_authoring: diyosp, Diyo Sukma Pradana
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_details: percentage
          plugin_followup: yes
          plugin_stars: yes
